name: health_inequity_simulation
channels:
  - defaults
dependencies:
  - jinja2
  - matplotlib=3.10.0
  - numpy=1.26.3
  - pip=23.3.1
  - plotly=5.19.0
  - scipy=1.11.4
  - setuptools=68.2.2
  - tqdm=4.65.0
  - pip:
      - black-it==0.3.1
      - neworder==1.4.2
      - pandas
      - scikit-learn==1.6.1
      - seaborn==0.12.2
      - statsmodels==0.14.4