name: final_test
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - attrs=23.1.0=py311h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py311hbed6279_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.2.25=h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.20=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mysql=5.7.24=h721c034_2
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.3=py311h08b1b3b_0
  - numpy-base=1.26.3=py311hf175353_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py311h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=23.2=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py311hcea889d_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - plotly=5.19.0=py311h92b7b1e_0
  - ply=3.11=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - python=3.11.7=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311h06a4308_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - scipy=1.11.4=py311h08b1b3b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - tzdata=2023d=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - asttokens==3.0.0
      - black-it==0.3.1
      - blosc2==3.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - cloudpickle==3.1.1
      - comm==0.2.2
      - decorator==5.2.1
      - executing==2.2.0
      - gymnasium==0.27.1
      - gymnasium-notices==0.0.1
      - idna==3.10
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - jax-jumpy==1.0.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - matplotlib-inline==0.1.7
      - msgpack==1.1.0
      - ndindex==1.9.2
      - neworder==1.4.2
      - pandas
      - pandas-stubs==2.2.3.250308
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - prompt-toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.1
      - requests==2.32.3
      - scikit-learn==1.6.1
      - seaborn==0.12.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tables==3.10.2
      - threadpoolctl==3.6.0
      - traitlets==5.14.3
      - types-pytz==2025.2.0.20250326
      - typing-extensions==4.13.0
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - xgboost==1.7.6
